# Generated by Django 5.1.4 on 2025-05-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
    ]
