# Generated by Django 5.1.4 on 2025-05-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_remove_appointment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
