# Generated by Django 5.1.4 on 2025-05-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0008_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
