# Generated by Django 5.1.4 on 2025-05-20 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctorapp', '0011_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('dob', models.DateField(help_text='Date of Birth in YYYY-MM-DD format')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender of the user', max_length=10)),
                ('contact_number', models.CharField(help_text='Unique contact number', max_length=20, unique=True)),
                ('address', models.TextField(blank=True, help_text='Full address of the user')),
            ],
        ),
    ]
