# Generated by Django 5.1.4 on 2025-05-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0013_patient_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
